analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.381647708825767
  brandStrength: 0.3665880954358727
  rhythmicContrast: 0.7953489802312106
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  lightness: 0.4732952495105565
typography_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0
favicon: null
name: savagecats
