name: savagecats
favicon: null
layout_spectrum: 0.10550470580346882
typography_spectrum: 0.032483838964253664
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3665880954358727
  lightness: 0.47329524951055646
  saturation: 0.38164770882576704
  rhythmicContrast: 0.7953489802312106
purpose: []
